### ISSUE TITLE
Alternate methods to input Esperanto special characters

### ISSUE THREAD

**Issue by ProfessorO** [ProfessorO/esperanta-analizisto#12]
Add buttons near the textarea to insert each of the 5 characters with diacriticals: ĉ ĝ ĥ ĵ ŝ ŭ. Oh, and capitalized ones, too. Though ŭ only comes after another vowel (just like j).

**Comment by stephenwade** [comment]
Convert x-digraphs (cx, gx, hx, etc.) and c^ as you type.
